### PR TITLE
query with my information

### PR DESCRIPTION
**Pull request by Camilo959**
adding query with my information

### CODE REVIEW

**Review by QuewarG — DISMISSED** [review]
Ok

**Review by OviedoSebastian — APPROVED** [review]
Okay

**Review by OviedoSebastian — APPROVED** [review]

**Review by OviedoSebastian — DISMISSED** [review]
Okay

**Review by OviedoSebastian — DISMISSED** [review]

**Review by DylanFarkas — DISMISSED** [review]
Ok 👍

**Review by Stiven-023 — APPROVED** [review]
Ok

**Review by DylanFarkas — APPROVED** [review]
Ok 👍

**Pull request merged**
