### PR TITLE
Feature/info jhoimar s

### PR DESCRIPTION
**Pull request by JhoimarSilva**

### CODE REVIEW

**Review by OviedoSebastian — APPROVED** [review]
ok

**Review by QuewarG — DISMISSED** [review]
ok

**Review by OviedoSebastian — DISMISSED** [review]
Ok

**Review by OviedoSebastian — DISMISSED** [review]

**Review by Camilo959 — DISMISSED** [review]
approved

**Review by OviedoSebastian — APPROVED** [review]

**Review by DylanFarkas — APPROVED** [review]
Ok 👍

**Review by Stiven-023 — APPROVED** [review]
Ok

**Pull request merged**
